# Generated by Django 5.1.4 on 2025-01-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mstravelapp', '0002_country_state_district_customuser'),
    ]

    operations = [
    ]
