# Generated by Django 5.1.4 on 2024-12-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginTable',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
