# Generated by Django 5.1.4 on 2025-01-04 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Prep_time', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('Vegetarian', models.BooleanField()),
                ('Description', models.CharField(max_length=5000)),
            ],
        ),
    ]
