# Generated by Django 5.1.4 on 2024-12-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auther_alter_book_price_alter_book_title_book_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='book_media'),
        ),
    ]
