# Generated by Django 5.1.4 on 2024-12-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='Recipe_img',
            field=models.ImageField(upload_to='recipe/'),
        ),
    ]
